app_name: DataExtractor
cli_name: data-extractor

beautify:
    .json:
        indent: "\t"
        prefix: ""
    else:
        indent: "\t"
        prefix: ""

colors:
    multi_select:
        .json:
            focused: "#FFE31A"
            selected: "#F09319"
        else:
            focused: "#01FAC6"
            selected: "170"
